### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by kummitus** [karvonen/NethackSokoban#1]
21.28 Ladattu

Ei kauheasti mitään mainittavaa. Metodit ovat ytimekkäitä ja selkeitä. Toiminnallisuus on jaettu.  Rivivaihtoja voisi ehkä olla enemmän niissä kohdin joissa alustetaan muuttujia ja kutsutaan muita metodeja. 

Peli voisi vaihtoehtoisesti toimia pelkästään painallusten perustella kun se ei kuitenkaan ole riippuvainen jatkuvasta ruudunpäivityksestä?

Kaikki testit menivät läpi. Rivikattavuudessa voisi olla parantamisen varaa.

**Comment by Melchan** [comment]
20.00 ladattu

Hyvä perus ilme koodissa. Helposti luettavaa ja jdocceja näyttäisi olevan kattavasti. 
Luokat on jaoteltu selkeisiin kansiohin. Luokkat näyttäisivät olevan tarpeeksi monessa osassa.

Pelin ulkoinen ilme on hyvä kun sitä tarkastelee. Selkeä ja kiva käyttöliittymä. Mahdollisuus lisätä mappeja on hyvä.
